Use CFITSIO library installed at prefix

diff --git a/astrotcl/configure b/astrotcl/configure
--- a/astrotcl/configure
+++ b/astrotcl/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CYGPATH EXEEXT PKG_LIB_FILE PKG_STUB_LIB_FILE PKG_STUB_SOURCES PKG_STUB_OBJECTS PKG_TCL_SOURCES PKG_HEADERS PKG_INCLUDES PKG_LIBS PKG_CFLAGS TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_LIBS TCL_DEFS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_SHLIB_LD_LIBS TK_VERSION TK_BIN_DIR TK_SRC_DIR TK_LIB_FILE TK_LIB_FLAG TK_LIB_SPEC TK_STUB_LIB_FILE TK_STUB_LIB_FLAG TK_STUB_LIB_SPEC TK_LIBS TK_XINCLUDES CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC OBJEXT CPP CXX CXXFLAGS ac_ct_CXX INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE RANLIB ac_ct_RANLIB EGREP MATH_LIBS tclutil_VERSION tclutil_LIB_FILE tclutil_BUILD_LIB_SPEC tclutil_LIB_SPEC BLT_LIB_SPEC tclutil_SRC_DIR my_shmem SHLIB_LD_CXX_LIBS PKG_SOURCES PKG_OBJECTS CLEANFILES TCL_INCLUDES TK_INCLUDES TCL_THREADS SHARED_BUILD AR CELIB_DIR LIBOBJS SHLIB_SUFFIX DL_LIBS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING STLIB_LD SHLIB_LD SHLIB_CFLAGS SHLIB_LD_LIBS LDFLAGS_DEBUG LDFLAGS_OPTIMIZE LD_LIBRARY_PATH_VAR TCL_DBGX CFLAGS_DEFAULT LDFLAGS_DEFAULT MAKE_LIB MAKE_SHARED_LIB MAKE_STATIC_LIB MAKE_STUB_LIB RANLIB_STUB TCLSH_PROG WISH_PROG astrotcl_LIB_FILE astrotcl_BUILD_DIR astrotcl_BUILD_LIB_SPEC astrotcl_LIB_SPEC astrotcl_PKG_OBJECTS astrotcl_SRC_DIR LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CYGPATH EXEEXT PKG_LIB_FILE PKG_STUB_LIB_FILE PKG_STUB_SOURCES PKG_STUB_OBJECTS PKG_TCL_SOURCES PKG_HEADERS PKG_INCLUDES PKG_LIBS PKG_CFLAGS TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_LIBS TCL_DEFS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_SHLIB_LD_LIBS TK_VERSION TK_BIN_DIR TK_SRC_DIR TK_LIB_FILE TK_LIB_FLAG TK_LIB_SPEC TK_STUB_LIB_FILE TK_STUB_LIB_FLAG TK_STUB_LIB_SPEC TK_LIBS TK_XINCLUDES CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC OBJEXT CPP CXX CXXFLAGS ac_ct_CXX INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE RANLIB ac_ct_RANLIB EGREP MATH_LIBS tclutil_VERSION tclutil_LIB_FILE tclutil_BUILD_LIB_SPEC tclutil_LIB_SPEC BLT_LIB_SPEC tclutil_SRC_DIR CFITSIO_LIB_SPEC my_shmem SHLIB_LD_CXX_LIBS PKG_SOURCES PKG_OBJECTS CLEANFILES TCL_INCLUDES TK_INCLUDES TCL_THREADS SHARED_BUILD AR CELIB_DIR LIBOBJS SHLIB_SUFFIX DL_LIBS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING STLIB_LD SHLIB_LD SHLIB_CFLAGS SHLIB_LD_LIBS LDFLAGS_DEBUG LDFLAGS_OPTIMIZE LD_LIBRARY_PATH_VAR CFITSIO_LIB_DIR TCL_DBGX CFLAGS_DEFAULT LDFLAGS_DEFAULT MAKE_LIB MAKE_SHARED_LIB MAKE_STATIC_LIB MAKE_STUB_LIB RANLIB_STUB TCLSH_PROG WISH_PROG astrotcl_LIB_FILE astrotcl_BUILD_DIR astrotcl_BUILD_LIB_SPEC astrotcl_LIB_SPEC astrotcl_PKG_OBJECTS astrotcl_SRC_DIR LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -870,6 +870,7 @@ Optional Packages:
   --with-tkinclude      directory containing the public Tk header files.
   --with-x                use the X Window System
   --with-celib=DIR        use Windows/CE support library from DIR
+  --with-cfitsio=DIR      link with CFITSIO library installed in DIR
 
 Some influential environment variables:
   CC          C compiler command
@@ -6677,6 +6678,7 @@ if test -f $cf ; then
 
 
 
+
 else
     { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
 echo "$as_me: error: $cf doesn't exist" >&2;}
@@ -7462,6 +7464,27 @@ _ACEOF
 # ==================== END OF cfitsio SECTION ================
 
 #------------------------------------------------------------------------
+# ASTROTCL_PATH_CFITSIO --
+#
+#	Locate the CFITSIO library
+#
+# Arguments:
+#	none
+#
+# Results:
+#
+#	Adds the following arguments to configure:
+#		--with-cfitsio=...
+#
+#	Defines the following vars:
+#		CFITSIO_LIB_SPEC      String to add to link the CFITSIO lib (-L... -lBLT)
+#		CFITSIO_LIB_DIR       Directory containing libcfitsio.so
+#------------------------------------------------------------------------
+
+
+
+
+#------------------------------------------------------------------------
 #  Check if we require additional libraries to support C++ shareable
 #  libraries.
 system=`uname -s`-`uname -r`
@@ -7509,10 +7532,10 @@ esac
 #-----------------------------------------------------------------------
 
 
-csources=`cd $srcdir; echo generic/*.[Cc] press/*.[Cc] libwcs/*.[Cc] cfitsio/*.[Cc]`
+csources=`cd $srcdir; echo generic/*.[Cc] press/*.[Cc] libwcs/*.[Cc]`
 
-cheaders=`cd $srcdir; echo generic/*.h press/*.h libwcs/*.h cfitsio/*.h`
-cincludes="-I$srcdir/../tclutil/generic -I$srcdir/generic -I$srcdir/press -I$srcdir/libwcs -I$srcdir/cfitsio"
+cheaders=`cd $srcdir; echo generic/*.h press/*.h libwcs/*.h`
+cincludes="-I$srcdir/../tclutil/generic -I$srcdir/generic -I$srcdir/press -I$srcdir/libwcs"
 tclsources=`cd $srcdir; echo library/*.tcl`
 
 
@@ -7570,7 +7593,7 @@ echo "$as_me: error: could not find header file '${srcdir}/$i'" >&2;}
 
 
 
-    vars="$tclutil_BUILD_LIB_SPEC ${BLT_LIB_SPEC}"
+    vars="$tclutil_BUILD_LIB_SPEC ${BLT_LIB_SPEC} ${CFITSIO_LIB_SPEC}"
     for i in $vars; do
 	if test "${TEA_PLATFORM}" = "windows" -a "$GCC" = "yes" ; then
 	    # Convert foo.lib to -lfoo for GCC.  No-op if not *.lib
@@ -7952,7 +7975,7 @@ ac_x_header_dirs='
 /usr/openwin/share/include'
 
 if test "$ac_x_includes" = no; then
-  # Guess where to find include files, by looking for Xlib.h.
+  # Guess where to find include files, by looking for Intrinsic.h.
   # First, try using that file with no special directory specified.
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -7960,7 +7983,7 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <X11/Xlib.h>
+#include <X11/Intrinsic.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -7987,7 +8010,7 @@ else
 sed 's/^/| /' conftest.$ac_ext >&5
 
   for ac_dir in $ac_x_header_dirs; do
-  if test -r "$ac_dir/X11/Xlib.h"; then
+  if test -r "$ac_dir/X11/Intrinsic.h"; then
     ac_x_includes=$ac_dir
     break
   fi
@@ -8001,18 +8024,18 @@ if test "$ac_x_libraries" = no; then
   # See if we find them without any special options.
   # Don't add to $LIBS permanently.
   ac_save_LIBS=$LIBS
-  LIBS="-lX11 $LIBS"
+  LIBS="-lXt $LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <X11/Xlib.h>
+#include <X11/Intrinsic.h>
 int
 main ()
 {
-XrmInitialize ()
+XtMalloc (0)
   ;
   return 0;
 }
@@ -11752,6 +11775,74 @@ echo "${ECHO_T}${tcl_cv_type_off64_t}" >&6
 
 
 #--------------------------------------------------------------------
+# Find the CFITSIO library.
+#--------------------------------------------------------------------
+
+    echo "$as_me:$LINENO: checking for CFITSIO library" >&5
+echo $ECHO_N "checking for CFITSIO library... $ECHO_C" >&6
+
+# Check whether --with-cfitsio or --without-cfitsio was given.
+if test "${with_cfitsio+set}" = set; then
+  withval="$with_cfitsio"
+  CFITSIO_LIB_DIR=$withval
+fi;
+
+    CFITSIO_LIBNAME=libcfitsio${SHLIB_SUFFIX}
+    CFITSIO_LIBFLAG=-lcfitsio
+
+    if test -z "$CFITSIO_LIB_DIR" ; then
+	# If --with-cfitsio=dir was not specified, try the exec-prefix/lib dir
+       	places="\
+		$exec_prefix/lib \
+		$prefix/lib \
+	"
+	for i in $places ; do
+		if test -f $i/$CFITSIO_LIBNAME
+		then
+       			CFITSIO_LIB_DIR=$i
+			break
+		fi
+	done
+        if test -z "$CFITSIO_LIB_DIR" ; then
+	     echo
+	     { { echo "$as_me:$LINENO: error: could not find $CFITSIO_LIBNAME: Please use the --with-cfitsio=DIR option." >&5
+echo "$as_me: error: could not find $CFITSIO_LIBNAME: Please use the --with-cfitsio=DIR option." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+    else
+       # Check if the CFITSIO library is in the lib subdir of the given dir
+       if test ! -f $CFITSIO_LIB_DIR/$CFITSIO_LIBNAME
+       then
+          if test ! -f $CFITSIO_LIB_DIR/lib/$CFITSIO_LIBNAME
+          then
+	     echo
+	     { { echo "$as_me:$LINENO: error: could not find $CFITSIO_LIBNAME in $CFITSIO_LIB_DIR or in $CFITSIO_LIB_DIR/lib: Please use the --with-cfitsio=DIR option." >&5
+echo "$as_me: error: could not find $CFITSIO_LIBNAME in $CFITSIO_LIB_DIR or in $CFITSIO_LIB_DIR/lib: Please use the --with-cfitsio=DIR option." >&2;}
+   { (exit 1); exit 1; }; }
+          else
+	    CFITSIO_LIB_DIR=$CFITSIO_LIB_DIR/lib
+          fi
+       fi
+    fi
+    CFITSIO_LIB_SPEC="-L$CFITSIO_LIB_DIR $CFITSIO_LIBFLAG"
+    echo "$as_me:$LINENO: result: $CFITSIO_LIB_DIR" >&5
+echo "${ECHO_T}$CFITSIO_LIB_DIR" >&6
+
+
+
+
+    vars="${CFITSIO_LIB_SPEC}"
+    for i in $vars; do
+	if test "${TEA_PLATFORM}" = "windows" -a "$GCC" = "yes" ; then
+	    # Convert foo.lib to -lfoo for GCC.  No-op if not *.lib
+	    i=`echo "$i" | sed -e 's/^\([^-].*\)\.lib$/-l\1/i'`
+	fi
+	PKG_LIBS="$PKG_LIBS $i"
+    done
+
+
+
+#--------------------------------------------------------------------
 # Set the default compiler switches based on the --enable-symbols option.
 #--------------------------------------------------------------------
 
@@ -12701,6 +12792,7 @@ s,@tclutil_BUILD_LIB_SPEC@,$tclutil_BUILD_LIB_SPEC,;t t
 s,@tclutil_LIB_SPEC@,$tclutil_LIB_SPEC,;t t
 s,@BLT_LIB_SPEC@,$BLT_LIB_SPEC,;t t
 s,@tclutil_SRC_DIR@,$tclutil_SRC_DIR,;t t
+s,@CFITSIO_LIB_SPEC@,$CFITSIO_LIB_SPEC,;t t
 s,@my_shmem@,$my_shmem,;t t
 s,@SHLIB_LD_CXX_LIBS@,$SHLIB_LD_CXX_LIBS,;t t
 s,@PKG_SOURCES@,$PKG_SOURCES,;t t
@@ -12725,6 +12817,7 @@ s,@SHLIB_LD_LIBS@,$SHLIB_LD_LIBS,;t t
 s,@LDFLAGS_DEBUG@,$LDFLAGS_DEBUG,;t t
 s,@LDFLAGS_OPTIMIZE@,$LDFLAGS_OPTIMIZE,;t t
 s,@LD_LIBRARY_PATH_VAR@,$LD_LIBRARY_PATH_VAR,;t t
+s,@CFITSIO_LIB_DIR@,$CFITSIO_LIB_DIR,;t t
 s,@TCL_DBGX@,$TCL_DBGX,;t t
 s,@CFLAGS_DEFAULT@,$CFLAGS_DEFAULT,;t t
 s,@LDFLAGS_DEFAULT@,$LDFLAGS_DEFAULT,;t t
